server:
  port: 9090
application:
  name: conta
spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:h2:~/conta
    username: root
    password: root
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
  kafka:
    properties:
      schema:
        registry:
          url: ${SCHEMA_REGISTRY_URL:http://localhost:8081}
    producer:
      bootstrap-servers: ${KAFKA_URL:http://localhost:9092}
      key-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      group-id: conta
topic:
  name:
    producer: NOVA_CONTA
